### ISSUE TITLE
Some bugs or problems

### ISSUE THREAD

**Issue by Ace-0** [VinaLx/service-computing-homework#5]
### Bugs
1. The discription of command `list` is empty.
2. When using the command `createMeeting`, only the first user following `-p` can be added to the participators of the meeting(users' names are split by space).
3. Thr function of flag `-y` in command `changeParticipators` is in contrast to its instructions. When using `-y AAA`, "AAA" should be deleted from the list of participators. But the program add it to the list.

### Problems
1. Even I shut down and restart my computer, I remained logged in. Should we fix this?
2. When using `createMeetings`, the time conflict of the host himself/herself is not taken into consideration.
3. When using `list`, the order of the list is random, that is, it is different every time. Well, it's harmless but interesting.

**Comment by VinaLx-zz** [comment]
1: ask@yzx :)
2: after -p, quote the user: like -p "user1 user2 user3"

**Comment by ZexinYan** [comment]
1: f**k
2: ask yourself
3: ask@VinaLx

**Comment by VinaLx-zz** [comment]
this repository is no longer maintained :P
